export default {
  /* login*/
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGIN_ERROR: 'LOGIN_ERROR',

  /* logout */
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  /* animal */
  GET_ANIMALS_REQUEST: 'GET_ANIMALS_REQUEST',
  GET_ANIMALS_SUCCESS: 'GET_ANIMALS_SUCCESS',
  GET_ANIMALS_FAIL: 'GET_ANIMALS_FAIL',
};
